server:
  port: 8011
spring:
  datasource:
    db1:
        jdbcUrl: jdbc:mysql://localhost:3306/mytest?characterEncoding=utf8&useSSL=false
        username: root
        password: ya123456
        driver-class-name: com.mysql.jdbc.Driver
    db2:
        jdbcUrl: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false
        username: root
        password: ya123456
        driver-class-name: com.mysql.jdbc.Driver
  redis:
    open: true
    database: 0
    host: 127.0.0.1
    post: 6379
    timeout: 5000
expiretime: 30
query:
  login:
    url: /hello?name=default
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: /var/log/tomcat/sell.log
#  level: com.imooc.LoggerTest: debug
